
db.type=mysql

# MySQL localhost (XAMPP)
#db.host=localhost
#db.port=3306
#db.name=taller_db
#db.user=root
#db.password=

 db.host=172.30.16.36
 db.user=damonroy86
 db.password=67001386

# SQLite
sqlite.url=jdbc:sqlite:C:\Users\sala7\Downloads\taller_db.sqlite
