# Configuracion de Conexion - Sistema de Taller

# Tipo de base de datos: mysql o sqlite
db.type=mysql

# MySQL localhost (XAMPP)
db.host=localhost
db.port=3306
db.name=taller_db
db.user=root
db.password=

# MySQL Windows (red) - cambiar host si es necesario
# db.host=172.30.16.52
# db.user=damonroy86
# db.password=67001386

# SQLite
db.file=taller_db.sqlite
